language: node_js
node_js:
- '0.10'
deploy:
  api_key:
    secure: OTZRp+XRXQaKdjkMHXHhQSMYye1mL9rfT0xXUcW5K3pTupG5+THaRFk4lNkstd2GDANtsoPSPzbfS3qEt5TK6Svc8/gZVQnVc2FNJ6VlhckHfC/xoOXeu9Pw7mFiKy2R92B4vRhoLrmT62NcDngyI8MWDhfpwLzywsP2cU+vyRg=
  email: sayed.hashimi@gmail.com
  provider: npm
  on:
    branch: release
